apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.51.50.18
    path: /mnt/raid/kubernetes
  persistentVolumeReclaimPolicy: Retain
